version: "3.4"

networks:
  postgres:

volumes:
  postgres-data:
  postgres-log:

services:
  database:
    image: postgres
    networks:
      - postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - postgres-log:/var/log/postgresql
    restart: always
    env_file: .env
    environment:
      POSTGRES_DB: ${FI_SWEETS_DB_NAME}
      POSTGRES_USER: ${FI_SWEETS_DB_USER}
      POSTGRES_PASSWORD: ${FI_SWEETS_DB_PASSWORD}

  server:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - postgres
    ports:
      - "7777:8080"
    env_file: .env
    environment:
      POSTGRES_URL: ${FI_SWEETS_DB_URL}
      POSTGRES_USER: ${FI_SWEETS_DB_USER}
      POSTGRES_PASSWORD: ${FI_SWEETS_DB_PASSWORD}