version: "3.4"

networks:
  postgres:

volumes:
  postgres-data:
  postgres-log:

services:
  database:
    image: postgres
    networks:
      - postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - postgres-log:/var/log/postgresql
    restart: always
    env_file: .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    networks:
      - postgres
    ports:
      - "7777:8080"
    env_file: .env
    volumes:
      - ./:/app
    environment:
      POSTGRES_URL: ${DB_URL}/${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET_TOKEN: ${JWT_SECRET_TOKEN}
      MINIO_HOST: ${MINIO_HOST}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_BUCKET: ${MINIO_BUCKET}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_SECRET_ENDPOINT: ${STRIPE_SECRET_ENDPOINT}
      EDAMAM_APP_ID: ${EDAMAM_APP_ID}
      EDAMAM_APP_KEY: ${EDAMAM_APP_KEY}
