server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  h2:
    console:
      enabled: true
  devtools:
    restart:
      enabled: true
  jpa:
    show-sql: true
    generate-ddl: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_USER}
    password: ${EMAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

minio:
  url: ${MINIO_HOST}
  bucket:
    name: ${MINIO_BUCKET}
  access:
    key: ${MINIO_ACCESS_KEY}
    secret: ${MINIO_SECRET_KEY}

stripe:
  secret-key: ${STRIPE_SECRET_KEY}
  secret-endpoint: ${STRIPE_SECRET_ENDPOINT}

logging:
  level:
    org:
      springframework:
        security: error

security:
  token:
    secret: ${JWT_SECRET_TOKEN}

apis:
  edamam:
    app-id: ${EDAMAM_APP_ID}
    app-key: ${EDAMAM_APP_KEY}

front:
  base-url: ${FRONT_BASE_URL}