name: DEV CI/CD

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  workflow_dispatch:

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/api:latest-dev

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Deploy on DEV server
        uses: fjogeleit/http-request-action@master
        with:
          url: ${{ secrets.WEBHOOK_DEV_SERVER_URL }}
          method: POST